#!/usr/bin/env python3
"""
Hook: Enforce calling roslyn_get_instructions("git") before git commit/push.

This hook validates that a git token was generated by the MCP server
before allowing git commit/push operations.

Tokens are per-solution (based on solution file hash) and valid for 1 minute.

Flow:
1. roslyn_get_instructions("git") generates a token and writes to ~/.claude/roslyn-git-token-{hash}
2. This hook reads the token and validates it via HTTP endpoint
3. If valid (< 1 min old), commit/push is allowed
"""
import sys
import json
import re
import os
import hashlib
import urllib.request
import urllib.error
import urllib.parse


def find_solution_file(start_dir=None):
    """Find the .sln or .slnx file by walking up from the start directory."""
    if start_dir is None:
        start_dir = os.getcwd()

    current = os.path.abspath(start_dir)

    # Walk up to 10 levels
    for _ in range(10):
        if not current or current == os.path.dirname(current):
            break

        # Check for solution files
        try:
            for ext in ['.slnx', '.sln']:
                for item in os.listdir(current):
                    if item.endswith(ext):
                        return os.path.join(current, item)
        except:
            pass

        current = os.path.dirname(current)

    return None


def get_solution_hash(solution_path):
    """Get a short hash of the solution path for unique token filename."""
    if not solution_path:
        return "global"
    # Use first 8 chars of MD5 hash
    return hashlib.md5(solution_path.lower().encode()).hexdigest()[:8]


def get_hook_port():
    """Read the port number from the port file."""
    port_file = os.path.join(os.path.expanduser('~'), '.claude', 'roslyn-hook-port')
    try:
        with open(port_file, 'r') as f:
            return int(f.read().strip())
    except:
        return None


def get_git_token(solution_path):
    """Read the git token from the per-solution token file."""
    solution_hash = get_solution_hash(solution_path)
    token_file = os.path.join(os.path.expanduser('~'), '.claude', f'roslyn-git-token-{solution_hash}')
    try:
        with open(token_file, 'r') as f:
            return f.read().strip()
    except:
        return None


def validate_token_http(token, port):
    """Validate token via HTTP endpoint."""
    try:
        encoded_token = urllib.parse.quote(token, safe='')
        url = f'http://localhost:{port}/validate?token={encoded_token}&topic=git'
        with urllib.request.urlopen(url, timeout=5) as response:
            data = json.loads(response.read().decode('utf-8'))
            return data.get('valid', False), data.get('message', 'Unknown error')
    except urllib.error.URLError as e:
        return False, f'Cannot connect to validation server: {e.reason}'
    except Exception as e:
        return False, f'Validation error: {e}'


def validate_token_local(token):
    """Fallback: validate token locally by checking timestamp."""
    try:
        parts = token.split('.')
        if len(parts) != 4:
            return False, 'Invalid token format'

        timestamp = int(parts[1])
        import time
        age_seconds = time.time() - timestamp

        if age_seconds > 60:  # 1 minute
            return False, f'Token expired ({age_seconds/60:.1f} minutes old, max 1 minute)'

        if age_seconds < 0:
            return False, 'Token timestamp is in the future'

        return True, f'Valid (local validation, {age_seconds:.0f}s old)'
    except Exception as e:
        return False, f'Local validation error: {e}'


def main():
    try:
        data = json.load(sys.stdin)
    except:
        sys.exit(0)  # Can't parse input, allow

    command = data.get('tool_input', {}).get('command', '')

    # Check if this is a git commit or push command
    if not re.search(r'git\s+(commit|push)', command):
        sys.exit(0)  # Not a commit/push, allow

    # Find solution file from current working directory
    solution_path = find_solution_file()

    # Get the token
    token = get_git_token(solution_path)
    if not token:
        solution_info = f' for {os.path.basename(solution_path)}' if solution_path else ''
        print(f'BLOCKED: No git token found{solution_info}.', file=sys.stderr)
        print('Run: roslyn_get_instructions(topic: "git") before committing.', file=sys.stderr)
        sys.exit(2)

    # Try HTTP validation first
    port = get_hook_port()
    if port:
        valid, message = validate_token_http(token, port)
    else:
        # Fallback to local validation
        valid, message = validate_token_local(token)

    if valid:
        sys.exit(0)  # Allow
    else:
        print(f'BLOCKED: {message}', file=sys.stderr)
        print('Run: roslyn_get_instructions(topic: "git") before committing.', file=sys.stderr)
        sys.exit(2)

if __name__ == '__main__':
    main()
