#!/usr/bin/env python3
"""
Hook: Enforce calling roslyn_get_instructions("git") before git commit/push.

This hook validates that a git token was generated by the MCP server
before allowing git commit/push operations.

Flow:
1. roslyn_get_instructions("git") generates a token and writes to ~/.claude/roslyn-git-token
2. This hook reads the token and validates it via HTTP endpoint
3. If valid (< 5 min old), commit/push is allowed
"""
import sys
import json
import re
import os
import urllib.request
import urllib.error
import urllib.parse

def get_hook_port():
    """Read the port number from the port file."""
    port_file = os.path.join(os.path.expanduser('~'), '.claude', 'roslyn-hook-port')
    try:
        with open(port_file, 'r') as f:
            return int(f.read().strip())
    except:
        return None

def get_git_token():
    """Read the git token from the token file."""
    token_file = os.path.join(os.path.expanduser('~'), '.claude', 'roslyn-git-token')
    try:
        with open(token_file, 'r') as f:
            return f.read().strip()
    except:
        return None

def validate_token_http(token, port):
    """Validate token via HTTP endpoint."""
    try:
        encoded_token = urllib.parse.quote(token, safe='')
        url = f'http://localhost:{port}/validate?token={encoded_token}&topic=git'
        with urllib.request.urlopen(url, timeout=5) as response:
            data = json.loads(response.read().decode('utf-8'))
            return data.get('valid', False), data.get('message', 'Unknown error')
    except urllib.error.URLError as e:
        return False, f'Cannot connect to validation server: {e.reason}'
    except Exception as e:
        return False, f'Validation error: {e}'

def validate_token_local(token):
    """Fallback: validate token locally by checking timestamp."""
    try:
        parts = token.split('.')
        if len(parts) != 4:
            return False, 'Invalid token format'

        timestamp = int(parts[1])
        import time
        age_seconds = time.time() - timestamp

        if age_seconds > 300:  # 5 minutes
            return False, f'Token expired ({age_seconds/60:.1f} minutes old)'

        if age_seconds < 0:
            return False, 'Token timestamp is in the future'

        return True, f'Valid (local validation, {age_seconds:.0f}s old)'
    except Exception as e:
        return False, f'Local validation error: {e}'

def main():
    try:
        data = json.load(sys.stdin)
    except:
        sys.exit(0)  # Can't parse input, allow

    command = data.get('tool_input', {}).get('command', '')

    # Check if this is a git commit or push command
    if not re.search(r'git\s+(commit|push)', command):
        sys.exit(0)  # Not a commit/push, allow

    # Get the token
    token = get_git_token()
    if not token:
        print('BLOCKED: No git token found.', file=sys.stderr)
        print('Run: roslyn_get_instructions(topic: "git") before committing.', file=sys.stderr)
        sys.exit(2)

    # Try HTTP validation first
    port = get_hook_port()
    if port:
        valid, message = validate_token_http(token, port)
    else:
        # Fallback to local validation
        valid, message = validate_token_local(token)

    if valid:
        sys.exit(0)  # Allow
    else:
        print(f'BLOCKED: {message}', file=sys.stderr)
        print('Run: roslyn_get_instructions(topic: "git") before committing.', file=sys.stderr)
        sys.exit(2)

if __name__ == '__main__':
    main()
