<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>RoslynMcpServer.Web</RootNamespace>
    <Version>1.0.0-rc</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RoslynMcpServer.Graph\RoslynMcpServer.Graph.csproj" />
  </ItemGroup>

</Project>
