<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SharpOps.Torch</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TorchSharp" />
    <PackageReference Include="libtorch-cuda-12.8-win-x64" />
    <PackageReference Include="TorchSharp.PyBridge" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpOps\SharpOps.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Models\**\*" CopyToOutputDirectory="PreserveNewest" Pack="false" CopyToPublishDirectory="Never" />
  </ItemGroup>

</Project>
